plugins {
    id 'com.android.application'
}

android {
    namespace 'az.marakana.mobile'
    compileSdk 35

    defaultConfig {
        applicationId 'az.marakana.mobile'
        minSdk 26
        targetSdk 35
        versionCode 35
        versionName '3.4.12-native-v35'
    }

    signingConfigs {
        release {
            def ksPath = System.getenv("MARAKANA_KEYSTORE_PATH")
            if (ksPath != null && !ksPath.isEmpty()) {
                storeFile file(ksPath)
                storePassword System.getenv("MARAKANA_KEYSTORE_PASSWORD")
                keyAlias System.getenv("MARAKANA_KEY_ALIAS")
                keyPassword System.getenv("MARAKANA_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-code-scanner:16.1.0'
}
